"""Vehicle constants -- GENERATED by `python3 -m fastdeploy sync`.

Do not edit. The source of truth is sim_mjc/sim_mjc/config.py:DRONE; change it
there and re-run sync, or this file will be overwritten.

Attitude and rate gains are the original hand-tuned values rescaled by the
inertia ratio (0.1154 in xy, 0.1125 in z), since
J*omegadot = Kp*eR - Kd*eOmega makes the closed loop depend on Kp/J. Position
gains are unscaled: they command an acceleration, independent of mass.
"""
import numpy as np

MASS = 1.25              # kg
GRAVITY = 9.81           # m/s^2
ARM = 0.15               # m, rotor offset along body x and y
K_M = 0.016             # m, yaw torque per newton of thrust
MAX_THRUST = 7.0        # N per rotor
TIMESTEP = 0.005          # s, matches dart.xml and sim_mjc

INERTIA = np.diag([0.0025, 0.0025, 0.0045])

POS_P_GAIN = np.diag([16.7, 16.7, 16.7])
VEL_P_GAIN = np.diag([7.2, 7.2, 7.2])
ATTITUDE_P_GAIN = np.diag([0.115385, 0.115385, 0.022500])
RATE_P_GAIN = np.diag([0.034615, 0.034615, 0.022500])

HOVER_THRUST_TOTAL = MASS * GRAVITY
HOVER_THRUST_PER_ROTOR = HOVER_THRUST_TOTAL / 4.0
TWR = 4.0 * MAX_THRUST / HOVER_THRUST_TOTAL
